services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.prd
    volumes:
    - static_volume:/app/staticfiles
    restart: unless-stopped
    env_file:
      - .env.production
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env.production
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # zodat je ook vanaf host kan connecten als je wilt

  nginx:
    image: nginx:latest
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot_data/etc:/etc/letsencrypt
      - ./certbot_data/var:/var/www/certbot
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    volumes:
      - ./certbot_data/etc:/etc/letsencrypt
      - ./certbot_data/var:/var/www/certbot
    restart: unless-stopped  
    entrypoint: >
      sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done"

volumes:
  pgdata:
  static_volume:


  