# Use official Python image
FROM python:3.12-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y build-essential

# Install Python dependencies
COPY ./app/requirements.txt /app/requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy project files
COPY ./app /app

# Expose port for Gunicorn
EXPOSE 8000

# Start Gunicorn
# 1 Worker
# CMD ["gunicorn", "mypaperhive.wsgi:application", "--bind", "0.0.0.0:8000"]
# 3 Workers
CMD ["gunicorn", "mypaperhive.wsgi:application", "--workers", "1", "--bind", "0.0.0.0:8000", "--timeout", "120"] 
